export const COMPUTER_PLAY = "COMPUTER_PLAY";
export const COMPUTER_THINK = "COMPUTER_THINK";
export const RESTART_GAME = "RESTART_GAME";
export const SELECT_CARD = "SELECT_CARD";
export const SELECT_PLANT = "SELECT_PLANT";
export const SET_TERRAIN = "SET_TERRAIN";
